/**
 * Table View Generator
 * Generates React table component with Tailwind styling
 */

/**
 * Generate table view component
 * @param {Object} config - Parsed configuration
 * @returns {string} React component code
 */
function generateTableView(config) {
    const { componentName, entityNamePascal, fields, layout } = config;
    
    return `/**
 * ${componentName}View Component
 * Generated by Prototype Line Generator
 * ${new Date().toISOString()}
 */

import React, { useState, useEffect, useMemo } from 'react';
import { ${entityNamePascal}, ${componentName}Props } from '../types/${componentName}Types';
import { mock${entityNamePascal}Data } from '../data/${componentName}MockData';

export const ${componentName}View: React.FC<${componentName}Props> = ({ 
    initialData,
    onRowClick,
    className = ''
}) => {
    // State management
    const [data, setData] = useState<${entityNamePascal}[]>([]);
    const [loading, setLoading] = useState(true);
    const [sortField, setSortField] = useState<keyof ${entityNamePascal} | null>(null);
    const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('asc');
    const [filterText, setFilterText] = useState('');
    const [currentPage, setCurrentPage] = useState(1);
    const [pageSize, setPageSize] = useState(10);

    // Load data
    useEffect(() => {
        const loadData = async () => {
            setLoading(true);
            // Simulate API call
            setTimeout(() => {
                setData(initialData || mock${entityNamePascal}Data);
                setLoading(false);
            }, 500);
        };
        loadData();
    }, [initialData]);

    // Sorting logic
    const handleSort = (field: keyof ${entityNamePascal}) => {
        if (sortField === field) {
            setSortDirection(sortDirection === 'asc' ? 'desc' : 'asc');
        } else {
            setSortField(field);
            setSortDirection('asc');
        }
    };

    // Filtering logic
    const filteredData = useMemo(() => {
        if (!filterText) return data;
        
        return data.filter(row => {
            return Object.values(row).some(value => 
                String(value).toLowerCase().includes(filterText.toLowerCase())
            );
        });
    }, [data, filterText]);

    // Sorting application
    const sortedData = useMemo(() => {
        if (!sortField) return filteredData;
        
        return [...filteredData].sort((a, b) => {
            const aVal = a[sortField];
            const bVal = b[sortField];
            
            if (aVal === null || aVal === undefined) return 1;
            if (bVal === null || bVal === undefined) return -1;
            
            if (aVal < bVal) return sortDirection === 'asc' ? -1 : 1;
            if (aVal > bVal) return sortDirection === 'asc' ? 1 : -1;
            return 0;
        });
    }, [filteredData, sortField, sortDirection]);

    // Pagination
    const paginatedData = useMemo(() => {
        const start = (currentPage - 1) * pageSize;
        const end = start + pageSize;
        return sortedData.slice(start, end);
    }, [sortedData, currentPage, pageSize]);

    const totalPages = Math.ceil(sortedData.length / pageSize);

    // Loading state
    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
            </div>
        );
    }

    return (
        <div className={\`space-y-4 \${className}\`}>
            {/* Header */}
            <div className="flex justify-between items-center">
                <h2 className="text-2xl font-bold text-gray-900">
                    ${config.hierarchy.module.name}
                </h2>
                <div className="text-sm text-gray-500">
                    {sortedData.length} records
                </div>
            </div>

            {/* Filter */}
            ${layout.features.filtering ? `<div className="flex gap-4">
                <input
                    type="text"
                    placeholder="Search..."
                    value={filterText}
                    onChange={(e) => setFilterText(e.target.value)}
                    className="px-4 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
            </div>` : ''}

            {/* Table */}
            <div className="overflow-x-auto shadow-md rounded-lg">
                <table className="min-w-full bg-white">
                    <thead className="bg-gray-50 border-b-2 border-gray-200">
                        <tr>
${fields.map(field => `                            <th 
                                className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider ${field.isSortable ? 'cursor-pointer hover:bg-gray-100' : ''}"
                                ${field.isSortable ? `onClick={() => handleSort('${field.fieldCamel}' as keyof ${entityNamePascal})}` : ''}
                            >
                                <div className="flex items-center gap-1">
                                    ${field.label}
                                    ${field.isSortable ? `{sortField === '${field.fieldCamel}' && (
                                        <span className="text-blue-600">
                                            {sortDirection === 'asc' ? '↑' : '↓'}
                                        </span>
                                    )}` : ''}
                                </div>
                            </th>`).join('\n')}
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200">
                        {paginatedData.map((row, index) => (
                            <tr 
                                key={index}
                                className="hover:bg-gray-50 transition-colors cursor-pointer"
                                onClick={() => onRowClick?.(row)}
                            >
${fields.map(field => `                                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                    ${renderFieldValue(field)}
                                </td>`).join('\n')}
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Pagination */}
            ${layout.features.pagination ? `<div className="flex justify-between items-center">
                <div className="flex gap-2">
                    <select
                        value={pageSize}
                        onChange={(e) => setPageSize(Number(e.target.value))}
                        className="px-3 py-1 border border-gray-300 rounded-md"
                    >
                        <option value={5}>5 per page</option>
                        <option value={10}>10 per page</option>
                        <option value={25}>25 per page</option>
                        <option value={50}>50 per page</option>
                    </select>
                </div>
                <div className="flex gap-2">
                    <button
                        onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                        disabled={currentPage === 1}
                        className="px-4 py-2 border border-gray-300 rounded-md disabled:opacity-50 hover:bg-gray-50"
                    >
                        Previous
                    </button>
                    <div className="px-4 py-2">
                        Page {currentPage} of {totalPages}
                    </div>
                    <button
                        onClick={() => setCurrentPage(prev => Math.min(totalPages, prev + 1))}
                        disabled={currentPage === totalPages}
                        className="px-4 py-2 border border-gray-300 rounded-md disabled:opacity-50 hover:bg-gray-50"
                    >
                        Next
                    </button>
                </div>
            </div>` : ''}
        </div>
    );
};

// Helper function to render field values with appropriate formatting
${generateFieldRenderer(fields, entityNamePascal)}
`;
}

/**
 * Generate field value renderer based on type
 */
function renderFieldValue(field) {
    if (field.type === 'boolean') {
        return `{row.${field.fieldCamel} ? '✓' : '✗'}`;
    } else if (field.type === 'enum' || field.type === 'status') {
        return `<span className={\`px-2 py-1 text-xs rounded-full \${getStatusColor(row.${field.fieldCamel})}\`}>
                                        {row.${field.fieldCamel}}
                                    </span>`;
    } else if (field.type === 'date') {
        return `{new Date(row.${field.fieldCamel}).toLocaleDateString()}`;
    } else {
        return `{row.${field.fieldCamel}}`;
    }
}

/**
 * Generate field renderer helper function
 */
function generateFieldRenderer(fields, entityType) {
    const hasStatus = fields.some(f => f.field === 'status' || f.type === 'enum');
    
    if (!hasStatus) return '';
    
    return `function getStatusColor(status: string): string {
    const colors: Record<string, string> = {
        'Active': 'bg-green-100 text-green-800',
        'Inactive': 'bg-gray-100 text-gray-800',
        'Pending': 'bg-yellow-100 text-yellow-800',
        'On Hold': 'bg-orange-100 text-orange-800',
        'Completed': 'bg-blue-100 text-blue-800',
        'Commercial': 'bg-purple-100 text-purple-800',
        'Residential': 'bg-indigo-100 text-indigo-800',
        'Industrial': 'bg-pink-100 text-pink-800'
    };
    return colors[status] || 'bg-gray-100 text-gray-800';
}`;
}

module.exports = {
    generateTableView
};