// Generated by Database Generator
// Iteration: 1
// Generated: 2025-08-23T21:57:19.127Z

export interface Database {
  public: {
    Tables: {
      account: {
        Row: {
          id: string
          account_number: string
          account_name: string
          account_type: string
          status: string
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          owner_id: string
          created_by: string
          created_at: string
        }
        Insert: {
          id?: string
          account_number: string
          account_name: string
          account_type: string
          status?: string
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip_code: string | null
          owner_id: string
          created_by: string
          created_at?: string
        }
      }
    }
  }
}