// US-006: Service Location Types
// Generated by TYPE-PROCESSOR for Value Slice 1

export interface ServiceLocation {
  id: string
  account_id: string
  location_name: string
  street_address: string
  city: string
  state: string
  postal_code: string
  access_information: string | null
  is_primary: boolean
  status: 'Active' | 'Inactive' | 'On-Hold'
  created_at: string
  updated_at: string
}

export interface ServiceLocationsResponse {
  locations: ServiceLocation[]
  pagination: {
    total: number
    page: number
    per_page: number
    total_pages: number
  }
}

export interface ServiceLocationsListProps {
  accountId: string
  accountName: string
  onLocationSelect?: (location: { id: string; name: string }) => void
  className?: string
}

export interface ServiceLocationsListState {
  locations: ServiceLocation[]
  loading: boolean
  error: string | null
}

export interface UseServiceLocationsResult {
  locations: ServiceLocation[]
  loading: boolean
  error: string | null
  refetch: () => void
}

export interface UseServiceLocationsOptions {
  accountId: string
  enabled?: boolean
}

export interface ServiceLocationCardProps {
  location: ServiceLocation
  className?: string
}
