/**
 * Work Order Type Definitions
 * Generated by TYPE-PROCESSOR
 * Story: US-007 - Work Orders for Selected Service Location
 */

export type WorkOrderType = 'Maintenance' | 'Repair' | 'Installation' | 'Inspection'
export type WorkOrderStatus = 'Scheduled' | 'Assigned' | 'In-Progress' | 'Completed' | 'Invoiced'
export type WorkOrderPriority = 'Low' | 'Medium' | 'High' | 'Emergency'

export interface WorkOrder {
  id: string
  service_location_id: string
  work_order_number: string
  type: WorkOrderType
  status: WorkOrderStatus
  priority: WorkOrderPriority
  scheduled_date: string
  scheduled_time_slot?: string
  technician_id?: string
  technician_name?: string
  description?: string
  completion_notes?: string
  created_at: string
  updated_at: string
}

export interface WorkOrdersListProps {
  locationId: string
  locationName: string
  onWorkOrderSelect?: (workOrderId: string) => void
  className?: string
}

export interface WorkOrderCardProps {
  workOrder: WorkOrder
  onClick?: () => void
  isSelected?: boolean
}

export interface WorkOrderDetailModalProps {
  workOrder: WorkOrder | null
  isOpen: boolean
  onClose: () => void
}

export interface UseWorkOrdersReturn {
  workOrders: WorkOrder[]
  loading: boolean
  error: string | null
  refetch: () => void
}

export interface WorkOrderFilters {
  status: WorkOrderStatus | 'all'
  priority: WorkOrderPriority | 'all'
  searchQuery: string
}
