/**
 * Type Definitions for AccountList
 * Generated by Prototype Line Generator
 * 2025-08-22T13:45:26.410Z
 */

// Entity type
export interface Account {
    accountName: string;
    accountNumber: string;
    accountType: string;
    status: string;
    locationName: string;
}

// Component props
export interface AccountListProps {
    initialData?: Account[];
    onRowClick?: (row: Account) => void;
    className?: string;
}

// Filter options
export interface AccountListFilterOptions {
    searchText?: string;
    accountTypeFilter?: string[];
    statusFilter?: string[];
}

// Sort options
export type AccountListSortField = keyof Account;
export type SortDirection = 'asc' | 'desc';

// Pagination options
export interface PaginationOptions {
    currentPage: number;
    pageSize: number;
    totalItems: number;
}

// API Response type (for future use)
export interface AccountListApiResponse {
    data: Account[];
    pagination: {
        page: number;
        pageSize: number;
        total: number;
        totalPages: number;
    };
}

// Form type (for create/edit)
export type AccountListFormData = Partial<Account>;

// Status type (if applicable)
export enum accountStatus {
    Active = 'Active',
    Inactive = 'Inactive',
    Pending = 'Pending',
    OnHold = 'On Hold',
    Completed = 'Completed'
}
