# .github/workflows/health-check.yml
name: Health Check

on:
  # DISABLED: Hourly health checks were annoying during development
  # To re-enable: uncomment the schedule section below
  # schedule:
  #   # Run every hour
  #   - cron: '0 * * * *'
  workflow_dispatch:  # Can still run manually from GitHub Actions tab

jobs:
  health-check:
    name: API Health Check
    runs-on: ubuntu-latest
    steps:
      - name: Check API Health
        run: |
          response=$(curl -s -w "\n%{http_code}" ${{ secrets.PRODUCTION_URL }}/api/health)
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          if [ "$http_code" != "200" ]; then
            echo "Health check failed with status $http_code"
            echo "Response: $body"
            exit 1
          fi
          
          echo "Health check passed"
          echo "Response: $body"